export const ENUM = {
  POKEMON_KEY:"pokemon",
  RIVAL_POKEMON_KEY:"rivalPokemon",
  OAK: "OAK",
  INITIAL: "initial",
  HOUSE: "House",
  GET_FROM_OAK: "Get one from Prof oak",
  CENTER: "Center",
  MART: "Mart",
  TABLE:"table",
  BALLS:"balls",
  NO_POKEMON: "You don't have any pokemon",
  PRESS_ENTER: "Press Enter to Enter the ",
  PICKONE:"PICK ONE BALL FROM THE TABLE",
  LOST_MESSAGE:">You lost $40",
  WON_MESSAGE:">You won +23 exp",
  CENTER_INSTRUCTION:"Touch the table and press Enter ",
  GIF_DEFAULT_FRONT:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/30.gif",
  GIF_DEFAULT_BACK:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/30.gif",
  EMPTY_STRING: " ",
  BATTLE: "battle",
  FONT_DESKTOP: "1.6rem",
  FONT_MOBILE: "1rem",
  COLORS: {
    BLACK: "black",
    BG_COLOR: "#6ece67",
    HOUSE:"#4B4FBD",
    BUILDING:"#b0ccd5",
    BUILDING_DOOR:"#73544f",
    ROAD:"#E8CBAC",
    TEXTBOX:"#b0aaaa",
  },
};
